### PR TITLE
Automate AWS availability zone selection

### LINKED ISSUE #668: Choose AWS Availability Zone that has the specified instance available
I was trying to create a CML runner, but it failed because

```
Error: Failed creating the machine: Not able to decode: operation error EC2: RunInstances,..., api error 
InsufficientInstanceCapacity: We currently do not have sufficient g4dn.2xlarge capacity in the Availability Zone you requested (eu-central-1b). 
Our system will be working on provisioning additional capacity. 
You can currently get g4dn.2xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1a, eu-central-1c."}
```

Would be great if TPI could:
- first, filter AZs in the specified region to those that have the instance required (see [here](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-type-not-supported-az-error/) how this is done)
- choose one of these AZs.

If request is done using spot fleet, you can probably just create launch templates for all AZs in the region.

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes #668, tested with this minimal example:

```hcl
terraform {
  required_providers {
    iterative = {
      source = "github.com/iterative/iterative"
    }
  }
}

provider "iterative" {}

resource "iterative_machine" "example" {
  cloud         = "aws"
  region        = "eu-central-1"
  instance_type = "g4dn.2xlarge"
}
```

### CODE REVIEW

File: iterative/aws/provider.go [hunk 1]
```diff
@@ -62,6 +62,32 @@ func ResourceMachineCreate(ctx context.Context, d *schema.ResourceData, m interf
...
+		}
+
+	loop:
+		for offeringsPaginator := ec2.NewDescribeInstanceTypeOfferingsPaginator(svc, offeringsInput); offeringsPaginator.HasMorePages(); {
+			page, err := offeringsPaginator.NextPage(ctx)
+			if err != nil {
+				return err
+			}
+
+			for _, offering := range page.InstanceTypeOfferings {
```
Comment (tasdomas) [inline iterative/aws/provider.go:84]: Do we need this loop here?

**Review by tasdomas — APPROVED** [review]
LGTM, though I think one of the loops is not necessary.

File: iterative/aws/provider.go (hunk 1 above)
Comment (0x2b3bfa0) [reply iterative/aws/provider.go:84]: Alternatively, we can write the same code like this:

```go
if len(page.InstanceTypeOfferings) > 0 {
        availabilityZone = aws.ToString(page.InstanceTypeOfferings[0].Location)
        break
}
```

Comment (0x2b3bfa0) [reply iterative/aws/provider.go:84]: @tasdomas, would you prefer the latter?

Comment (tasdomas) [reply iterative/aws/provider.go:84]: I would - it's a bit more explicit, but I'm fine with the PR as it is.

File: iterative/aws/provider.go [hunk 2]
```diff
@@ -62,6 +62,32 @@ func ResourceMachineCreate(ctx context.Context, d *schema.ResourceData, m interf
 	}
 	svc := ec2.NewFromConfig(config)
 
+	// Availability zone
+	if availabilityZone == "" {
```
Comment (tadejsv) [inline iterative/aws/provider.go:66]: Small comment: this could be moved to after line 247, as it's only needed if subnetId is not provided.

File: iterative/aws/provider.go (hunk 1 above)
Comment (0x2b3bfa0) [reply iterative/aws/provider.go]: Resolved with https://github.com/iterative/terraform-provider-iterative/pull/670/commits/6df5da68d3c7e480680b93a5137a30a65b09ff7f

Comment (0x2b3bfa0) [reply iterative/aws/provider.go]: @tasdomas, now “dr[y]er” with https://github.com/iterative/terraform-provider-iterative/pull/670/commits/8efff82ef80abd7e0574e0d8e1162675108e7ebf

**Review by dacbd — APPROVED** [review]
Hard to test reliably but I'm good with it for now and will revisit a better attempt at testing later.
[/note to self ](https://github.com/iterative/cml-playground/blob/main/workflows/tpi-670.yml)

File: iterative/aws/provider.go (hunk 2 above)
Comment (0x2b3bfa0) [reply iterative/aws/provider.go]: https://github.com/iterative/terraform-provider-iterative/pull/670/commits/729aa586bb8fef149733a1a93ecb667e66d2f9ae

**Review by casperdcl — COMMENTED** [review]
does `DescribeInstanceTypeOfferings` need to be documented in https://github.com/iterative/terraform-provider-iterative/blob/master/docs/guides/permissions/aws/main.tf?

**Comment by 0x2b3bfa0** [comment]
* https://github.com/iterative/terraform-provider-iterative/pull/689

**Comment by dacbd** [comment]
I dont think this is used by task...?
https://cml.dev/doc/ref/runner#common-permissions

**Comment by 0x2b3bfa0** [comment]
No, it's not

**Comment by dacbd** [comment]
sorry, also meant to put this on the link documentation PR...
