### PR TITLE
Use AWS DLAMI instead on NVIDIA NGC

### LINKED ISSUE #524: task: generic option combinations not working
Some useful generic option combinations don't work:

```hcl
resource "iterative_task" ... {
  cloud   = "aws"
  image   = "nvidia"
  spot    = 0

  # willing to change this, need cheapest possible GPU:
  machine = "m+k80"
  region  = "us-east"
  ...
}
```

```
│ Error: operation error Auto Scaling: CreateAutoScalingGroup, https response error StatusCode: 
400, RequestID: 3c6bae3f-56f2-4a27-a0b5-e46b7323ae9b, api error ValidationError:
You must use a valid fully-formed launch template. The instance configuration for this
AWS Marketplace product is not supported. Please see the AWS Marketplace site
for more information about supported instance types, regions, and operating systems.
```

`machine` working:

- `g4dn.xlarge`
- `l+v100`

not working:

- `m+{k80,v100}`
- `l+k80`

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
The best we can do to fix #524

### CODE REVIEW

File: task/aws/resources/data_source_image.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func (i *Image) Read(ctx context.Context) error {
 	image := i.Identifier
 	images := map[string]string{
 		"ubuntu": "ubuntu@099720109477:x86_64:*ubuntu/images/hvm-ssd/ubuntu-focal-20.04*",
-		"nvidia": "ubuntu@679593333241:x86_64:NVIDIA Deep Learning  AMI v21.02.2-*",
+		"nvidia": "ubuntu@898082745236:x86_64:Deep Learning AMI GPU TensorFlow 2.8.0 (Ubuntu 20.04) *",
```
Comment (casperdcl) [inline task/aws/resources/data_source_image.go:37]:
```suggestion
		"nvidia": "ubuntu@898082745236:x86_64:Deep Learning AMI GPU CUDA 11.2.1 (Ubuntu 20.04) 20220306",
```
