### PR TITLE
Task status, heavy write fix and aws ips 

### LINKED ISSUE #297: `task` tfstate shows all the ips from other tasks
This is something was happening to me in the xpd provider however in tpi seems to be fine, unless you see the logs and you can see that there is still 🤔 . While in logs we do not care in the tfstate is not desirable because the user wont be able to recover the IP to connect with the instance.

```json
{
  "version": 4,
  "terraform_version": "0.14.5",
  "serial": 5,
  "lineage": "ea085f62-0775-6cc2-b83c-f544b2fd1bde",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "xpd_task",
      "name": "taskfashion_mnist-1475236089",
      "provider": "provider[\"registry.terraform.io/0x2b3bfa0/xpd\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "addresses": [
              "52.53.238.219",
              "54.67.111.235",
              "54.176.177.41",
              "54.183.234.78",
              "54.193.29.29",
              "54.177.169.14",
              "13.52.243.72",
              "54.176.92.64",
              "54.153.73.154",
              "52.53.188.211",
              "54.67.35.59",
              "54.241.198.49",
              "13.52.177.33",
              "54.153.63.234",
              "13.52.78.123",
              "3.101.20.19",
              "54.183.96.208",
              "54.176.239.209",
              "3.101.40.217",
              "18.144.6.13",
              "3.101.40.168",
              "18.144.88.205",
              "54.215.107.58",
              "54.153.54.170",
              "52.53.254.37",
              "13.52.103.177",
              "54.183.234.170",
              "13.57.31.36",
              "13.52.252.110",
              "13.56.213.245",
              "52.53.171.206",
              "54.215.98.144",
              "13.57.225.64",
              "13.52.187.243",
              "54.153.66.2",
              "54.183.244.53",
              "54.241.154.90",
              "54.183.20.94",
              "54.183.25.248",
              "3.101.154.72",
              "54.219.244.204",
              "13.57.204.59",
              "54.193.64.234",
              "18.144.23.191",
              "52.53.217.112",
              "54.183.198.228",
              "54.241.93.131",
              "52.53.213.188",
      
```

```sh
Terraform will perform the following actions:

  # iterative_task.task1 will be destroyed
  - resource "iterative_task" "task1" {
      - addresses       = [
          - "52.53.238.219",
          - "54.67.111.235",
          - "54.176.177.41",
          - "54.183.234.78",
          - "54.193.29.29",
          - "54.177.169.14",
          - "54.176.92.64",
          - "54.153.73.154",
          - "52.53.188.211",
          - "54.67.35.59",
          - "13.52.177.33",
          - "54.153.63.234",
          - "3.101.20.19",
          - "54.183.96.208",
          - "54.176.239.209",
          - "3.101.40.217",
          - "18.144.6.13",
          - "3.101.40.168",
          - "18.144.88.205",
          - "54.215.107.58",
          - "54.153.54.170",
          - "52.53.254.37",
          - "13.52.103.177",
          - "54.183.234.170",
          - "13.57.31.36",
          - "13.52.252.110",
         
```

### LINKED ISSUE #319: `task` status field is not consistent enough
Im pretending to use the task status to do a check in the ci however does not seems effective enough, the reason is that seems that terminated status is present in the very first run?!!

```sh
if terraform show --json | grep "terminated Client.UserInitiatedShutdown"; then
  # this will run even in the first CI run
  echo 'Destroying...'
  terraform destroy --auto-approve -var "name=${NAME}"

  cml send-github-check --token=$GITHUB_TOKEN --conclusion=success --title='Training Model' report.md
  cml pr --md output/* >> report.md
  cml send-comment --update report.md
  cml send-comment --update --pr --commit-sha HEAD report.md
else
  echo 'Creating report...'
  echo 'training model...' > report.md
  cml send-github-check --token=$GITHUB_TOKEN --conclusion=neutral --title='Training Model' report.md
fi
```

We need:
 - Consistent ONE word statuses across the cloud vendors:
    - running
    - terminated
    - failed

This is the status in AWS (a bit weird I might say):

```json
"status":{
"running":38,
"terminated Client.UserInitiatedShutdown: User initiated shutdown":6
},
```

### LINKED ISSUE #321: `task` Write and Read to S3 is heavy
Lets do the math here of what would a user expect with a common ML project.
I had 450M writes and 950M reads across a few hundred tasks. Probably this is not real usage and I suspect that dangled tasks where actually also doing S3 ops.

### LINKED ISSUE #330: `task` creation does not complete
From time to time the task creation timeouts. The task seems to be created fine in the cloud but never ready for TF

image

```tf
terraform {
    required_providers {
        iterative = {
            source = "iterative/iterative",
        }
    }
}

provider "iterative" {}

resource "iterative_task" "tpi-examples-basic" {
    name      = "tpi-examples-basic"
    cloud     = "az"
    region    = "us-west"
    machine   = "Standard_D2S_v3"
    spot      = 0
    directory = "."

    environment = {
        EPOCHS = 1
    }

    script = <<-END
    #!/bin/bash
    sudo apt update && sudo apt-get install -y software-properties-common build-essential python3-pip
    python3 --version
    pip3 install -r requirements.txt
    python3 train.py
    END
}
```

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
- Closes #319; see [#318](https://github.com/iterative/terraform-provider-iterative/pull/318#issuecomment-982728169) for an explanation of the `ExecStart=-` syntax.
 - closes #321 with (guess it) pure `bash` 
 - closes #297 with https://github.com/iterative/terraform-provider-iterative/pull/322/commits/b7520b08a8a441e63d1717fe39c9e7f62657e721 unless proven otherwise.
 - partially fixes #330

### CODE REVIEW

File: task/common/machine/script.go [hunk 1]
```diff
@@ -41,12 +41,16 @@ while IFS= read -rd $'\0' variable; do
...
+TPI_LOG_DIRECTORY="$(mktemp --directory)"
+
 sudo tee /etc/systemd/system/tpi-task.service > /dev/null <<END
 [Unit]
   After=default.target
 [Service]
   Type=simple
-  ExecStart=/usr/bin/tpi-task
+  ExecStart=-/usr/bin/tpi-task
+  ExecStop=/bin/bash -c 'systemctl is-system-running | grep stopping || echo $SERVICE_RESULT $EXIT_CODE $EXIT_STATUS > "$TPI_LOG_DIRECTORY/machine-$TPI_MACHINE_IDENTITY" && rclone copy "$TPI_LOG_DIRECTORY" "$RCLONE_REMOTE/log"'
```
Comment (0x2b3bfa0) [inline task/common/machine/script.go:53]:
```suggestion
  ExecStop=/bin/bash -c 'systemctl is-system-running | grep stopping || echo $SERVICE_RESULT $EXIT_CODE $EXIT_STATUS > "$TPI_LOG_DIRECTORY/status-$TPI_MACHINE_IDENTITY" && rclone copy "$TPI_LOG_DIRECTORY" "$RCLONE_REMOTE/log"'
```

**Comment by DavidGOrtega** [comment]
I would put all that logic inside tpi stop. That would examine the logs and determine if we are OK, failed, etc...

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 should I take this one?

**Comment by 0x2b3bfa0** [comment]
If there isn't a draft pull request by tomorrow morning, 👍🏼

**Comment by DavidGOrtega** [comment]
Should I take it?

**Comment by 0x2b3bfa0** [comment]
⌛ 🏃🏼 😓 Pushing things in a few minutes if there isn't any ontehr unexpected issue. It's going to be “plan b” standing for bash, though. 😄

**Comment by 0x2b3bfa0** [comment]
```hcl
terraform {
  required_providers {
    iterative = {
      source = "github.com/iterative/iterative"
    }
  }
}

provider "iterative" {}

resource "iterative_task" "succeeded" {
  name  = "succeeded"
  cloud = "aws"
  script = "#!/bin/sh\nexit 0"
}

resource "iterative_task" "failed" {
  name  = "failed"
  cloud = "aws"
  script = "#!/bin/sh\nexit 1"
}

resource "iterative_task" "running" {
  name  = "running"
  cloud = "aws"
  script = "#!/bin/sh\nsleep infinity"
}
```


```console
$ terraform show

# iterative_task.succeeded:
resource "iterative_task" "succeeded" {
    ···
    status          = {
        "running"   = 0
        "succeeded" = 1
    }
}

# iterative_task.failed:
resource "iterative_task" "failed" {
    ···
    status          = {
        "failed"  = 1
        "running" = 0
    }
}

# iterative_task.running:
resource "iterative_task" "running" {
    ···
    status          = {
        "running" = 1
    }
}
```

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 `running` == 1 is during the whole cycle? I mean... when it starts but not yet running the user's code is running==1?

**Comment by 0x2b3bfa0** [comment]
Yes, `running` is about the machine, not about the task. We assume that a `running` machine will eventually run the user script.

**Comment by DavidGOrtega** [comment]
Sounds good. A nitpick would be that I prefer one status vs a composed status... but both are equivalent to some extend

File: task/common/values.go [hunk 2]
```diff
@@ -26,7 +26,9 @@ type Status map[StatusCode]int
 type StatusCode string
 
 const (
-	StatusCodeRunning StatusCode = "running"
+	StatusCodeActive    StatusCode = "running"
+	StatusCodeSucceeded StatusCode = "succeeded"
```
Comment (DavidGOrtega) [inline task/common/values.go:30]: `success` sounds better and a more widely used work in APIs

File: task/gcp/resources/resource_instance_group_manager.go [hunk 3]
```diff
@@ -75,9 +75,9 @@ func (i *InstanceGroupManager) Read(ctx context.Context) error {
 	}
 
 	i.Attributes.Addresses = []net.IP{}
-	i.Attributes.Status = common.Status{common.StatusCodeRunning: 0}
+	i.Attributes.Status = common.Status{common.StatusCodeActive: 0}
 	for _, groupInstance := range groupInstances.Items {
-		i.Attributes.Status[common.StatusCode(groupInstance.Status)]++
+		// DEBUG i.Attributes.Status[common.StatusCode(groupInstance.Status)]++
```
Comment (DavidGOrtega) [inline task/gcp/resources/resource_instance_group_manager.go:80]: unused?

File: task/aws/resources/resource_auto_scaling_group.go [hunk 4]
```diff
@@ -132,7 +132,10 @@ func (a *AutoScalingGroup) Read(ctx context.Context) error {
 				if instance.StateReason != nil {
 					status += " " + aws.ToString(instance.StateReason.Message)
 				}
-				a.Attributes.Status[common.StatusCode(status)]++
+				if status == "running" {
+					a.Attributes.Status[common.StatusCodeActive]++
+				}
+				// DEBUG a.Attributes.Status[common.StatusCode(status)]++
```
Comment (DavidGOrtega) [inline task/aws/resources/resource_auto_scaling_group.go]: unused?

File: task/aws/resources/resource_auto_scaling_group.go [hunk 5]
```diff
@@ -113,28 +113,33 @@ func (a *AutoScalingGroup) Read(ctx context.Context) error {
...
+			for _, reservation := range page.Reservations {
+				for _, instance := range reservation.Instances {
+					status := string(instance.State.Name)
+					if instance.StateReason != nil {
+						status += " " + aws.ToString(instance.StateReason.Message)
+					}
+					if status == "running" {
+						a.Attributes.Status[common.StatusCodeActive]++
+					}
+					// DEBUG a.Attributes.Status[common.StatusCode(status)]++
```
Comment (DavidGOrtega) [inline task/aws/resources/resource_auto_scaling_group.go:139]: unused?

File: task/az/resources/resource_virtual_machine_scale_set.go [hunk 6]
```diff
@@ -224,17 +224,17 @@ func (v *VirtualMachineScaleSet) Read(ctx context.Context) error {
...
+	v.Attributes.Status = common.Status{common.StatusCodeActive: 0}
 	scaleSetView, err := v.Client.Services.VirtualMachineScaleSets.GetInstanceView(ctx, v.Dependencies.ResourceGroup.Identifier, v.Identifier)
 	if err != nil {
 		return err
 	}
 	if scaleSetView.VirtualMachine.StatusesSummary != nil {
 		for _, status := range *scaleSetView.VirtualMachine.StatusesSummary {
 			code := to.String(status.Code)
-			v.Attributes.Status[common.StatusCode(code)] = int(to.Int32(status.Count))
+			// DEBUG v.Attributes.Status[common.StatusCode(code)] = int(to.Int32(status.Count))
```
Comment (DavidGOrtega) [inline task/az/resources/resource_virtual_machine_scale_set.go:235]: I guess that this is a terraformic thingy or unused?

File: task/common/machine/storage.go [hunk 7]
```diff
@@ -14,23 +15,31 @@ import (
...
+}
+
+func Reports(ctx context.Context, remote, prefix string) ([]string, error) {
 	remoteFileSystem, err := fs.NewFs(ctx, remote)
 	if err != nil {
 		return nil, err
 	}
 
-	entries, err := remoteFileSystem.List(ctx, "/log")
+	entries, err := remoteFileSystem.List(ctx, "/reports")
```
Comment (DavidGOrtega) [inline task/common/machine/storage.go:34]: why reports vs logs?

File: task/gcp/task.go [hunk 8]
```diff
@@ -352,8 +352,12 @@ func (t *Task) Events(ctx context.Context) []common.Event {
 	return t.Attributes.Events
 }
 
-func (t *Task) Status(ctx context.Context) common.Status {
-	return t.Attributes.Status
+func (t *Task) Status(ctx context.Context) (common.Status, error) {
```
Comment (DavidGOrtega) [inline task/gcp/task.go:355]: This function is repeated 3 times 😅

Comment (DavidGOrtega) [reply task/gcp/task.go:355]: I think it could go in the generic task?

**Review by DavidGOrtega — COMMENTED** [review]
Fast nitpicks while finishing review

File: task/common/values.go (hunk 2 above)
Comment (0x2b3bfa0) [reply task/common/values.go:30]: Tell that to Kubernetes developers. :smiling_imp: I'm being a bit facetious, of course, and agree that succeeded sounds a bit strange, but it's probably the only grammatically consistent option for that term. 😅

🔔 @casperdcl and your dictionary of synonyms.

Comment (DavidGOrtega) [reply task/common/values.go:30]: > but it's probably the only grammatically consistent option for that term. 

Also success

File: task/gcp/task.go (hunk 8 above)
Comment (0x2b3bfa0) [reply task/gcp/task.go:355]: Not quite, because of the same architectural issue on https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r750507783. If you find a (subjectively) more elegant way, feel free to follow up.

File: task/common/machine/storage.go (hunk 7 above)
Comment (0x2b3bfa0) [reply task/common/machine/storage.go:34]: Logs were exclusively a line–based file with the standard output/error of the task script. Reports are a wider concept, that includes exit statuses and — soon — also a key/value dictionary with status reports from the trianing code (e.g. DVC)

Comment (0x2b3bfa0) [reply task/common/machine/storage.go:34]: Maybe not the best word, but it's not part of the public API, so we can change it anytime we want.

**Comment by 0x2b3bfa0** [comment]
> _I prefer one status vs a composed status_

How would that “one status” look like? Sounds interesting.

**Comment by DavidGOrtega** [comment]
> > _I prefer one status vs a composed status_
> 
> How would that “one status” look like? Sounds interesting.

We have already design this previously. As stated in #319 
running, terminated, failed and migrating... something like that we defined

**Comment by DavidGOrtega** [comment]
- opens #356 
- opens #357
