### PR TITLE
Fix smoke test script preamble

### LINKED ISSUE #675: Fix broken shebang on smoke test script
### Continuation of https://github.com/iterative/terraform-provider-iterative/pull/673#discussion_r974478041

Shells try to interpret executable files even if they don't have a valid shebang, but the new string's shebang is broken due to the initial indentation whitespace. While this is not breaking tests, it would be nice to fix the string so the `-e` option becomes effective again.

#### Before #673 
https://github.com/iterative/terraform-provider-iterative/blob/672acef656f83f31ca36764a92e10b146fb02469/task/task_test.go#L83-L90

#### After #673 
https://github.com/iterative/terraform-provider-iterative/blob/7461e69db5a0f2e6a82931113369ae7e8143e1ae/task/task_smoke_test.go#L94-L102

### PR DESCRIPTION
**Pull request by tasdomas**
Closes #675.

### CODE REVIEW

File: task/task_smoke_test.go [hunk 1]
```diff
@@ -91,14 +90,13 @@ func TestTaskSmoke(t *testing.T) {
...
-          sleep 60
-          cat output/file
+	script := `#!/bin/sh -e
+                   test -v TEST_GPU && nvidia-smi
+                   mkdir --parents cache output
+                   touch cache/file
+                   echo "$ENVIRONMENT_VARIABLE_DATA" | tee --append output/file
+                   sleep 60
+                   cat output/file
         `[1:]
```
Comment (0x2b3bfa0) [inline task/task_smoke_test.go:100]:
```suggestion
        `
```

Cough, cough

**Review by 0x2b3bfa0 — CHANGES_REQUESTED** [review]

**Comment by 0x2b3bfa0** [comment]
@tasdomas, please check https://github.com/iterative/terraform-provider-iterative/pull/676/commits/9c5fadff7984088b8c51e715bc1400a7ca9736a0 before merging; I assumed that the indentation with spaces was an error of the editor.

**Review by 0x2b3bfa0 — APPROVED** [review]
Thanks!

**Comment by 0x2b3bfa0** [comment]
I feel trigger-happy today. Merging... :shipit:
